// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.0.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Rogue.Ptb.UI.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Export/import")]
    public partial class ExportImportFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ImportExport.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Export/import", "In order to retain my taskboards through upgrades\r\nAs a user\r\nI want to export my" +
                    " tasks to XML and import them back", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Export tasks")]
        public virtual void ExportTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Export tasks", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table1.AddRow(new string[] {
                        "Foo"});
            table1.AddRow(new string[] {
                        "Bar"});
            table1.AddRow(new string[] {
                        "Baz"});
#line 8
    testRunner.Given("that the following tasks already exist and are loaded:", ((string)(null)), table1);
#line 13
    testRunner.And("that everything is saved");
#line 14
    testRunner.And("that I enter \"C:\\foo\\bar.taskboard\" in the export taskboard dialog");
#line 15
    testRunner.When("I click export task");
#line 16
    testRunner.Then("the tasks should be exported to a \"C:\\foo\\bar.taskboard\"");
#line 17
    testRunner.And("the exported tasks should contain 3 tasks");
#line 18
    testRunner.And("task #2 in the exported tasks should have the title \"Bar\"");
#line 19
    testRunner.And("the exported tasks should not have empty IDs");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Import tasks")]
        public virtual void ImportTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Import tasks", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table2.AddRow(new string[] {
                        "Sidious"});
            table2.AddRow(new string[] {
                        "Tyranus"});
            table2.AddRow(new string[] {
                        "Malak"});
#line 23
    testRunner.Given("an export file containing these tasks at \"C:\\foo\\export.xml\"", ((string)(null)), table2);
#line 28
    testRunner.And("I create a new taskboard");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table3.AddRow(new string[] {
                        "Caedus"});
            table3.AddRow(new string[] {
                        "Plagueis"});
#line 29
    testRunner.And("that the following tasks already exist and are loaded:", ((string)(null)), table3);
#line 33
    testRunner.And("that I enter \"C:\\foo\\export.xml\" in the import taskboard dialog");
#line 34
    testRunner.When("I click import tasks");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table4.AddRow(new string[] {
                        "Sidious"});
            table4.AddRow(new string[] {
                        "Tyranus"});
            table4.AddRow(new string[] {
                        "Malak"});
            table4.AddRow(new string[] {
                        "Caedus"});
            table4.AddRow(new string[] {
                        "Plagueis"});
#line 35
    testRunner.Then("the taskboard should contain these tasks:", ((string)(null)), table4);
#line 42
    testRunner.And("the loaded tasks should not have empty IDs");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Export/import")]
        public virtual void ExportImport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Export/import", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
    testRunner.Given("a varied set of tasks loaded into the taskboard");
#line 46
    testRunner.And("that I enter \"C:\\foo\\importexport.xml\" in the export taskboard dialog");
#line 47
    testRunner.And("that I enter \"C:\\foo\\importexport.xml\" in the import taskboard dialog");
#line 48
    testRunner.And("that I enter \"C:\\foo\\taskboard.taskboard\" in the create taskboard dialog");
#line 49
    testRunner.When("I click export task");
#line 50
    testRunner.And("I create a new taskboard");
#line 51
    testRunner.And("I click import tasks");
#line 52
    testRunner.Then("the loaded tasks should have the same attributes as the original set of tasks");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
