// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.0.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.431
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Rogue.Ptb.UI.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Creating new tasks")]
    public partial class CreatingNewTasksFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NewTask.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Creating new tasks", "In order to remember stuff that needs to be done\r\nAs a person\r\nI want to be able " +
                    "to add new tasks", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new tasks")]
        public virtual void AddNewTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new tasks", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table1.AddRow(new string[] {
                        "Yo"});
#line 7
 testRunner.Given("that the following tasks already exist and are loaded:", ((string)(null)), table1);
#line 10
    testRunner.When("I click new task");
#line 11
    testRunner.Then("a new task should be created");
#line 12
    testRunner.And("the new task should be displayed first");
#line 13
    testRunner.And("the new task should be in edit mode");
#line 14
 testRunner.And("the new task should be selected");
#line 15
    testRunner.And("the task should not be started");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Current task should be deselected when adding new task")]
        public virtual void CurrentTaskShouldBeDeselectedWhenAddingNewTask()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Current task should be deselected when adding new task", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("an open taskboard");
#line 19
 testRunner.When("I click new task");
#line 20
 testRunner.And("I click new task");
#line 21
 testRunner.Then("the new task should be selected");
#line 22
 testRunner.And("task #2 should not be selected");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Created date")]
        public virtual void CreatedDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Created date", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("an open taskboard");
#line 26
    testRunner.When("I click new task");
#line 27
    testRunner.Then("the new task should have a created date like now");
#line 28
    testRunner.And("the new task should have a modified date like now");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subtasks")]
        public virtual void Subtasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subtasks", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table2.AddRow(new string[] {
                        "Yo"});
#line 31
 testRunner.Given("that the following tasks already exist and are loaded:", ((string)(null)), table2);
#line 34
 testRunner.When("I select task \'Yo\'");
#line 35
 testRunner.And("click new subtask");
#line 36
 testRunner.Then("a new task should be created");
#line 37
 testRunner.And("the new task should be in edit mode");
#line 38
 testRunner.And("the new task should be in position #2");
#line 39
 testRunner.And("the new task should be indented 1 place");
#line 40
 testRunner.And("the new task should be selected");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subtasks of subtasks")]
        public virtual void SubtasksOfSubtasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subtasks of subtasks", ((string[])(null)));
#line 42
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table3.AddRow(new string[] {
                        "Yo"});
#line 43
 testRunner.Given("that the following tasks already exist and are loaded:", ((string)(null)), table3);
#line 46
 testRunner.When("I select task \'Yo\'");
#line 47
 testRunner.And("click new subtask");
#line 48
 testRunner.And("click new subtask");
#line 49
 testRunner.Then("a new task should be created");
#line 50
 testRunner.And("the new task should be in edit mode");
#line 51
 testRunner.And("the new task should be in position #3");
#line 52
 testRunner.And("the new task should be indented 2 places");
#line 53
 testRunner.And("the new task should be selected");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
