// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Rogue.Ptb.UI.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Create taskboard")]
    public partial class CreateTaskboardFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TaskBoardManagement.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Create taskboard", "In order to organize my tasks\r\nAs an enterprising person\r\nI want to create and op" +
                    "en taskboards", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create new taskboard")]
        public virtual void CreateNewTaskboard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create new taskboard", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("that I enter \"C:\\foo\\bar.taskboard\" in the create taskboard dialog");
#line 8
testRunner.When("I create a new taskboard");
#line 9
testRunner.Then("a new taskboard database should be created in \"C:\\foo\\bar.taskboard\"");
#line 10
testRunner.And("a new taskboard should be loaded");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Open existing taskboard")]
        public virtual void OpenExistingTaskboard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Open existing taskboard", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
testRunner.Given("that I enter \"C:\\foo\\bar.taskboard\" in the open taskboard dialog");
#line 14
testRunner.When("I open a taskboard");
#line 15
testRunner.Then("a taskboard should be loaded from \"C:\\foo\\bar.taskboard\"");
#line 16
testRunner.And("a new taskboard should be loaded");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remember the last opened taskboards")]
        public virtual void RememberTheLastOpenedTaskboards()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remember the last opened taskboards", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
testRunner.Given("that I open \"C:\\foo\\bar.taskboard\"");
#line 20
testRunner.And("that I open \"C:\\bar\\foo.taskboard\"");
#line 21
testRunner.And("that I open \"C:\\barbar\\foofoo.taskboard\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Path"});
            table1.AddRow(new string[] {
                        "C:\\bar\\foo.taskboard"});
            table1.AddRow(new string[] {
                        "C:\\foo\\bar.taskboard"});
#line 22
testRunner.Then("the dropdown for the open button should display these in this order:", ((string)(null)), table1);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No remembered open taskboards")]
        public virtual void NoRememberedOpenTaskboards()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No remembered open taskboards", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
testRunner.Then("the dropdown for the open button should contain no items");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Export tasks")]
        public virtual void ExportTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Export tasks", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table2.AddRow(new string[] {
                        "Foo"});
            table2.AddRow(new string[] {
                        "Bar"});
            table2.AddRow(new string[] {
                        "Baz"});
#line 31
testRunner.Given("that the following tasks already exist and are loaded:", ((string)(null)), table2);
#line 36
testRunner.And("that everything is saved");
#line 37
testRunner.And("that I enter \"C:\\foo\\bar.taskboard\" in the export taskboard dialog");
#line 38
testRunner.When("I click export task");
#line 39
testRunner.Then("the tasks should be exported to a \"C:\\foo\\bar.taskboard\"");
#line 40
testRunner.And("the exported tasks should contain 3 tasks");
#line 41
testRunner.And("task #2 in the exported tasks should have the title \"Bar\"");
#line 42
testRunner.And("the exported tasks should not have empty IDs");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Import tasks")]
        public virtual void ImportTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Import tasks", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table3.AddRow(new string[] {
                        "Sidious"});
            table3.AddRow(new string[] {
                        "Tyranus"});
            table3.AddRow(new string[] {
                        "Malak"});
#line 45
testRunner.Given("an export file containing these tasks at \"C:\\foo\\export.xml\"", ((string)(null)), table3);
#line 50
testRunner.And("I create a new taskboard");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table4.AddRow(new string[] {
                        "Caedus"});
            table4.AddRow(new string[] {
                        "Plagueis"});
#line 51
testRunner.And("that the following tasks already exist and are loaded:", ((string)(null)), table4);
#line 55
testRunner.And("that I enter \"C:\\foo\\export.xml\" in the import taskboard dialog");
#line 56
testRunner.When("I click import tasks");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title"});
            table5.AddRow(new string[] {
                        "Sidious"});
            table5.AddRow(new string[] {
                        "Tyranus"});
            table5.AddRow(new string[] {
                        "Malak"});
            table5.AddRow(new string[] {
                        "Caedus"});
            table5.AddRow(new string[] {
                        "Plagueis"});
#line 57
testRunner.Then("the taskboard should contain these tasks:", ((string)(null)), table5);
#line 64
testRunner.And("the loaded tasks should not have empty IDs");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
