// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Rogue.Ptb.UI.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Tooltips")]
    public partial class TooltipsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TaskToolTip.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tooltips", "In order to get more information about tasks\r\nAs a user\r\nI want tooltips to show " +
                    "me information", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
    testRunner.Given("that the thread culture is \'nb-no\'");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Tooltip 1")]
        public virtual void Tooltip1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tooltip 1", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table1.AddRow(new string[] {
                        "CreatedDate",
                        "26.01.2005 15:55"});
            table1.AddRow(new string[] {
                        "StartedDate",
                        "27.01.2006 8:32"});
            table1.AddRow(new string[] {
                        "StateChangedDate",
                        "27.01.2006 8:32"});
            table1.AddRow(new string[] {
                        "ModifiedDate",
                        "27.01.2006 19:23"});
#line 10
 testRunner.Given("a task with the following attributes:", ((string)(null)), table1);
#line hidden
#line 16
    testRunner.Then("the tooltip should show", "Created: 26.01.2005 15:55 \r\nLast modified: 27.01.2006 19:23\r\nStarted: 27.01.2006 " +
                    "08:32\r\nState last changed: 27.01.2006 08:32", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Tooltip 2")]
        public virtual void Tooltip2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tooltip 2", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table2.AddRow(new string[] {
                        "CreatedDate",
                        "26.01.2005 15:55"});
            table2.AddRow(new string[] {
                        "StartedDate",
                        "27.01.2006 8:32"});
            table2.AddRow(new string[] {
                        "CompletedDate",
                        "27.02.2006 8:32"});
            table2.AddRow(new string[] {
                        "StateChangedDate",
                        "27.02.2006 8:32"});
            table2.AddRow(new string[] {
                        "ModifiedDate",
                        "27.01.2006 19:23"});
#line 25
 testRunner.Given("a task with the following attributes:", ((string)(null)), table2);
#line hidden
#line 32
    testRunner.Then("the tooltip should show", "Created: 26.01.2005 15:55 \r\nLast modified: 27.01.2006 19:23\r\nStarted: 27.01.2006 " +
                    "08:32\r\nCompleted: 27.02.2006 08:32\r\nState last changed: 27.02.2006 08:32", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Tooltip 3")]
        public virtual void Tooltip3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tooltip 3", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table3.AddRow(new string[] {
                        "CreatedDate",
                        "26.01.2005 15:55"});
            table3.AddRow(new string[] {
                        "StartedDate",
                        "27.01.2006 8:32"});
            table3.AddRow(new string[] {
                        "AbandonedDate",
                        "27.02.2006 8:32"});
            table3.AddRow(new string[] {
                        "StateChangedDate",
                        "27.02.2006 8:32"});
            table3.AddRow(new string[] {
                        "ModifiedDate",
                        "27.01.2006 19:23"});
#line 42
 testRunner.Given("a task with the following attributes:", ((string)(null)), table3);
#line hidden
#line 49
    testRunner.Then("the tooltip should show", "Created: 26.01.2005 15:55 \r\nLast modified: 27.01.2006 19:23\r\nStarted: 27.01.2006 " +
                    "08:32\r\nAbandoned: 27.02.2006 08:32\r\nState last changed: 27.02.2006 08:32", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
